# Generated by Django 4.2.30 on 2026-06-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('hiring_requirement', models.TextField()),
                ('language_needed', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=200)),
                ('hiring_volume', models.PositiveIntegerField()),
                ('work_location', models.CharField(max_length=200)),
                ('budget_range', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
