# Generated by Django 4.2.30 on 2026-06-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('languages_known', models.CharField(max_length=300)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('preferred_location', models.CharField(max_length=200)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
